-- PROGRESSION - 1


-- 1. **Create table city**
CREATE TABLE CITY(
id number(11),
name VARCHAR(50) NOT NULL,
CONSTRAINT CITY_PK PRIMARY KEY(id)
);

-- 2. **Create table referee**
CREATE TABLE REFEREE(
id number(11),
name VARCHAR(50) NOT NULL,
CONSTRAINT REFEREE_PK PRIMARY KEY(id)
);


-- 3. **Create table innings**
CREATE TABLE INNINGS(
id number(11),
innings_number number(11) NOT NULL,
CONSTRAINT INNINGS_PK PRIMARY KEY(id)
);

-- 4. **Create table extra_type**
CREATE TABLE EXTRA_TYPE(
id number(11),
name VARCHAR(50) NOT NULL,
CONSTRAINT EXTRA_TYPE_PK PRIMARY KEY(id)
);

-- 5. **Create table skill**

CREATE TABLE SKILL(
id number(11),
name VARCHAR(50) NOT NULL,
CONSTRAINT SKILL_PK PRIMARY KEY(id)
);

-- 6. **Create table team**
CREATE TABLE TEAM(
id number(11),
name VARCHAR(50) NOT NULL,
coach VARCHAR(50) NOT NULL,
home_city number(11),
captain NUMBER(11) NOT NULL,
CONSTRAINT fk_CITY
FOREIGN KEY(home_city)
REFERENCES CITY(ID),
CONSTRAINT TEAM_PK PRIMARY KEY(id)
);


-- 7. **Create table player**
CREATE TABLE PLAYER(
id NUMBER(11),
name VARCHAR(50) NOT NULL,
country VARCHAR(50) NOT NULL,
skill_id NUMBER(11)NOT NULL,
team_id NUMBER(11)NOT NULL,
CONSTRAINT FK_SKILL
FOREIGN KEY (SKILL_ID)
REFERENCES SKILL(ID),
CONSTRAINT FK_TEAM
FOREIGN KEY (TEAM_ID)
REFERENCES TEAM(ID),
CONSTRAINT player PRIMARY KEY(id)
);


-- 8. **Create table venue**
CREATE TABLE VENUE(
id NUMBER(11),
stadium_name VARCHAR(50) NOT NULL,
CONSTRAINT venue PRIMARY KEY(id),
city_id NUMBER(11) NOT NULL,
CONSTRAINT fk_CITY1
FOREIGN KEY (CITY_ID)
REFERENCES CITY(ID)
);

-- 9. **Create table event**

CREATE TABLE EVENTS(
id NUMBER(11),
CONSTRAINT event PRIMARY KEY(id),
innings_id NUMBER(11)NOT NULL,
CONSTRAINT fk_INNINGS
FOREIGN KEY (INNINGS_ID)
REFERENCES INNINGS(ID),
events_no NUMBER(11)NOT NULL,
raider_id NUMBER(11)NOT NULL,
CONSTRAINT fk_PLAYER
FOREIGN KEY (RAIDER_ID)
REFERENCES PLAYER(ID),
raider_points NUMBER(11)NOT NULL,
defending_points NUMBER(11)NOT NULL,
clock_in_seconds NUMBER(11)NOT NULL,
team_one_score NUMBER(11)NOT NULL,
team_two_score NUMBER(11)NOT NULL
);


-- 10. **Create table extra_event**

CREATE TABLE EXTRA_EVENT(
  id NUMBER(11) PRIMARY KEY,
  event_id NUMBER(11) NOT NULL,
  extra_type_id NUMBER(11) NOT NULL,
  points NUMBER(11) NOT NULL,
  scoring_team_id NUMBER(11) NOT NULL,
  CONSTRAINT FK_EVENT_ID FOREIGN KEY (event_id) REFERENCES EVENTS(id),
  CONSTRAINT FK_EXTRA_TYPE FOREIGN KEY (extra_type_id) REFERENCES EXTRA_TYPE(id),
  CONSTRAINT FK_SCORE_ID FOREIGN KEY (scoring_team_id) REFERENCES TEAM(id)
);

-- 11. **Create table outcome**
CREATE TABLE OUTCOME(
id NUMBER(11),
status VARCHAR(100) NOT NULL,
winner_team_id NUMBER(11),
CONSTRAINT FK_WINNER
FOREIGN KEY (WINNER_TEAM_ID)
REFERENCES TEAM(ID),
score NUMBER(11) NULL,
player_of_match NUMBER(11),
CONSTRAINT FK_PLAYER1
FOREIGN KEY (PLAYER_OF_MATCH)
REFERENCES PLAYER(ID),
CONSTRAINT TABLE_PK PRIMARY KEY(id)
);

-- 12. **Create table game**

CREATE TABLE GAME(
id NUMBER(11),
CONSTRAINT game PRIMARY KEY(id),
game_date DATE NOT NULL,
team_id_1 NUMBER(11),
CONSTRAINT FK_TEAM_ID_1
FOREIGN KEY (TEAM_ID_1)
REFERENCES TEAM(ID),
team_id_2 NUMBER(11),
CONSTRAINT FK_TEAM_ID_2
FOREIGN KEY (TEAM_ID_2)
REFERENCES TEAM(ID),
venue_id NUMBER(11),
CONSTRAINT FK_VENUE_ID
FOREIGN KEY (VENUE_ID)
REFERENCES VENUE(ID),
outcome_id NUMBER(11),
CONSTRAINT FK_OUTCOME_ID
FOREIGN KEY (OUTCOME_ID)
REFERENCES OUTCOME(ID),
referee_id_1 NUMBER(11),
CONSTRAINT FK_REFEREE_ID_1
FOREIGN KEY (REFEREE_ID_1)
REFERENCES REFEREE(ID),
referee_id_2 NUMBER(11),
CONSTRAINT FK_REFEREE_ID_2
FOREIGN KEY (REFEREE_ID_2)
REFERENCES REFEREE(ID),
first_innings_id NUMBER(11),
CONSTRAINT FK_FIRST_INNINGS_ID
FOREIGN KEY (FIRST_INNINGS_ID)
REFERENCES INNINGS(ID),
second_innings_id NUMBER(11),
CONSTRAINT FK_SECOND_INNINGS_ID
FOREIGN KEY (SECOND_INNINGS_ID)
REFERENCES INNINGS(ID)
);

-- 13. **Drop table city**

ALTER TABLE TEAM
DROP CONSTRAINT FK_CITY;
    
ALTER TABLE VENUE DROP CONSTRAINT FK_CITY1;

DROP TABLE CITY;


-- 14. **Drop table innings**
ALTER TABLE EVENTS DROP CONSTRAINT fk_INNINGS;
ALTER TABLE GAME drop CONSTRAINT FK_FIRST_INNINGS_ID;
ALTER TABLE GAME DROP CONSTRAINT FK_SECOND_INNINGS_ID;

DROP TABLE INNINGS;


-- 15. **Drop table skill**
ALTER TABLE PLAYER DROP CONSTRAINT FK_SKILL;
DROP TABLE SKILL;


-- 16. **Drop table extra_type**
ALTER TABLE EXTRA_EVENT DROP CONSTRAINT FK_EXTRA_TYPE;
DROP TABLE EXTRA_TYPE;
